// Re-export shared types for frontend usage
export {
    type Owner,
    type PaymentMethod,
    type ExpenseType,
    type PaymentStatus,
    type Category,
    type Income,
    type Expense,
    type Settings,
    type MonthlyOverview,
    type MonthlyStats,
    DEFAULT_SETTINGS,
    PAYMENT_METHODS,
    PAYMENT_STATUS_LABELS,
    PAYMENT_STATUS_ICONS,
    PAYMENT_METHOD_ICONS,
    getPaymentMethodLabel,
    getOwnerLabel,
    formatCurrency,
    formatYearMonth,
    getCurrentYearMonth,
    addMonths,
    isCurrentMonth,
} from './shared/types.js';
